In [1]:
import pandas as pd
from sklearn.preprocessing import minmax_scale
import numpy as np
from scipy.stats import multivariate_normal
import sklearn as sk
from sklearn import covariance
from sklearn.metrics import confusion_matrix, classification_report
import math

def distance(x,y):
    n = len(x)
    d = 0
    for i in range(n):
        d = d+(x[i]-y[i])**2
    return d**0.5


def nearest(x_0,cl,k):
    n = len(x_0)  #Dimension
    num = len(cl) #number pf samples
    dist = np.zeros(num)
    dist2 = np.zeros(num)
    for i in range(num):
        dist[i] = distance(x_0,cl[i])
        dist2[i] = distance(x_0,cl[i])
        
    dist.sort()
    idx = [list(dist2).index(i) for i in dist[0:k]]
    
    return idx
    
trainData = pd.read_csv('pendigitstrain.csv')
testData = pd.read_csv('pendigitstest.csv')

TrainLabel = trainData['17']
TestLabel = testData['17']

TrainFeat = trainData.drop(['17'],axis = 1)
TestFeat = testData.drop(['17'],axis = 1)

TrainFeatScaled = minmax_scale(TrainFeat, feature_range = (0,1))
TestFeatScaled = minmax_scale(TestFeat, feature_range = (0,1))


N_T = len(TrainFeatScaled)

def decision(x, k):
    G = nearest(x,TrainFeatScaled,k)
    Classes = [TrainLabel[i] for i in G]
    num_Classes = np.zeros(10)
    for i in Classes:
        if i==0:
            num_Classes[0]+=1
        elif i==1:
            num_Classes[1]+=1
        elif i==2:
            num_Classes[2]+=1
        elif i==3:
            num_Classes[3]+=1
        elif i==4:
            num_Classes[4]+=1
        elif i==5:
            num_Classes[5]+=1
        elif i==6:
            num_Classes[6]+=1
        elif i==7:
            num_Classes[7]+=1
        elif i==8:
            num_Classes[8]+=1
        elif i==9:
            num_Classes[9]+=1
    
        
    return list(num_Classes).index(num_Classes.max())

TestDecision = np.zeros((len(TestLabel),1))
K = [1, 3, 5, 10]

for k in K:
    CCR = 0
    for i in range(len(TestDecision)):
        x = TestFeatScaled[i][:]
        TestDecision[i][0]=decision(x, k)
        if TestDecision[i][0] == TestLabel[i]:
            CCR += 1



    print('k = {}, CCR = {}'.format(k, CCR/len(TestLabel)))

k = 1, CCR = 0.9774156660949114
k = 3, CCR = 0.9779874213836478
k = 5, CCR = 0.9759862778730704
k = 10, CCR = 0.9754145225843339


In [2]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3, metric='minkowski',p=2)
knn.fit(TrainFeatScaled, TrainLabel)

TestDecision = knn.predict(TestFeatScaled)

print(confusion_matrix(TestDecision, TestLabel, [0, 1,2,3,4,5,6,7,8,9]))
print(classification_report(TestDecision, TestLabel))

[[354   0   0   0   0   0   0   0   1   0]
 [  0 350   2   1   0   0   0  10   0   3]
 [  0  11 362   0   0   0   0   1   0   0]
 [  0   0   0 333   0   5   0   0   0   7]
 [  0   1   0   0 354   0   0   0   0   1]
 [  0   0   0   0  10 328   0   0   1   1]
 [  5   0   0   0   0   0 336   1   0   0]
 [  0   2   0   0   0   0   0 351   0   4]
 [  3   0   0   0   0   0   0   1 334   1]
 [  1   0   0   2   0   2   0   0   0 319]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       355
           1       0.96      0.96      0.96       366
           2       0.99      0.97      0.98       374
           3       0.99      0.97      0.98       345
           4       0.97      0.99      0.98       356
           5       0.98      0.96      0.97       340
           6       1.00      0.98      0.99       342
           7       0.96      0.98      0.97       357
           8       0.99      0.99      0.99       339
           9       0.95     

C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\validation.py:71: FutureWarning: Pass labels=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)
