In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import minmax_scale
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

Data = pd.read_csv('retailMarketing.csv')

labels = Data['Age']
data = Data.drop(['Age'],axis=1)

columns = data.columns
data = data.drop([columns[0]],axis=1)
data.head()

Salary  Children  AmountSpent  Gender_Female  Gender_Male  OwnHome_Own  \
0   47500         0        755.0              1            0            1   
1   63600         0       1318.0              0            1            0   
2   13500         0        296.0              1            0            0   
3   85600         1       2436.0              0            1            1   
4   68400         0       1304.0              1            0            1   

   OwnHome_Rent  Married_Married  Married_Single  Location_Close  \
0             0                0               1               0   
1             1                0               1               1   
2             1                0               1               1   
3             0                1               0               1   
4             0                0               1               1   

   Location_Far  History_High  History_Low  History_Medium  Catalogs_6  \
0             1             0            1               0           1   
1             0             0            0               1           1   
2             0             0            0               1           0   
3             0             1            0               0           0   
4             0             1            0               0           0   

   Catalogs_12  Catalogs_18  Catalogs_24  
0            0            0            0  
1            0            0            0  
2            0            1            0  
3            0            1            0  
4            1            0            0

In [14]:
columns = data.columns
cols_to_norm = [columns[0], columns[1], columns[2]]
data[cols_to_norm] = data[cols_to_norm].apply(lambda x: (x-x.min())/(x.max()-x.min()))
data.head()

Salary  Children  AmountSpent  Gender_Female  Gender_Male  OwnHome_Own  \
0  0.281398  0.000000     0.121441              1            0            1   
1  0.376777  0.000000     0.211999              0            1            0   
2  0.079976  0.000000     0.047611              1            0            0   
3  0.507109  0.333333     0.391829              0            1            1   
4  0.405213  0.000000     0.209747              1            0            1   

   OwnHome_Rent  Married_Married  Married_Single  Location_Close  \
0             0                0               1               0   
1             1                0               1               1   
2             1                0               1               1   
3             0                1               0               1   
4             0                0               1               1   

   Location_Far  History_High  History_Low  History_Medium  Catalogs_6  \
0             1             0            1               0           1   
1             0             0            0               1           1   
2             0             0            0               1           0   
3             0             1            0               0           0   
4             0             1            0               0           0   

   Catalogs_12  Catalogs_18  Catalogs_24  
0            0            0            0  
1            0            0            0  
2            0            1            0  
3            0            1            0  
4            1            0            0

In [18]:
ages = labels.unique()
target = np.zeros(len(labels))
for i in range(len(target)):
    if labels[i]==ages[0]:
        target[i]=0
    elif labels[i]==ages[1]:
        target[i]=1
    elif labels[i]==ages[2]:
        target[i]=2
        
Target = pd.DataFrame(target)
Target.head()

0
0  0.0
1  1.0
2  2.0
3  1.0
4  1.0

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(data, Target, test_size=0.3, random_state=42, stratify=Target)

In [22]:
from sklearn import svm
from sklearn.metrics import confusion_matrix, classification_report

In [24]:
svc = svm.SVC()
svc.fit(X_train, Y_train.values.ravel())
Y_pred = svc.predict(X_test)
print(confusion_matrix(Y_test, Y_pred, [0, 1, 2]))
print(classification_report(Y_test, Y_pred))

[[ 17  32  13]
 [  4 120  28]
 [  3  20  63]]
              precision    recall  f1-score   support

         0.0       0.71      0.27      0.40        62
         1.0       0.70      0.79      0.74       152
         2.0       0.61      0.73      0.66        86

    accuracy                           0.67       300
   macro avg       0.67      0.60      0.60       300
weighted avg       0.67      0.67      0.65       300



C:\Program Files\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [26]:
Lisvm = svm.LinearSVC(C=0.5)
Lisvm.fit(X_train, Y_train.values.ravel())
Y_pred2 = Lisvm.predict(X_test)
print(confusion_matrix(Y_test, Y_pred2, [0, 1, 2]))
print(classification_report(Y_test, Y_pred2))

[[ 26  21  15]
 [ 10 136   6]
 [  7  13  66]]
              precision    recall  f1-score   support

         0.0       0.60      0.42      0.50        62
         1.0       0.80      0.89      0.84       152
         2.0       0.76      0.77      0.76        86

    accuracy                           0.76       300
   macro avg       0.72      0.69      0.70       300
weighted avg       0.75      0.76      0.75       300



In [27]:
Lisvm = svm.LinearSVC(C=2)
Lisvm.fit(X_train, Y_train.values.ravel())
Y_pred2 = Lisvm.predict(X_test)
print(confusion_matrix(Y_test, Y_pred2, [0, 1, 2]))
print(classification_report(Y_test, Y_pred2))

[[ 26  21  15]
 [ 11 137   4]
 [  7  12  67]]
              precision    recall  f1-score   support

         0.0       0.59      0.42      0.49        62
         1.0       0.81      0.90      0.85       152
         2.0       0.78      0.78      0.78        86

    accuracy                           0.77       300
   macro avg       0.73      0.70      0.71       300
weighted avg       0.75      0.77      0.76       300

